// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CoinCollection.Models;

public partial class Coin
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal OriginalValue { get; set; }

    public decimal RetailValue { get; set; }

    public int AmountMade { get; set; }

    public string ImagePath { get; set; }

    public string Description { get; set; }

    public virtual ICollection<CoinDate> CoinDates { get; set; } = new List<CoinDate>();
}