// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace CoinCollection.Models;

public partial class LocalDBMSSQLLocalDBContext : DbContext
{
    public LocalDBMSSQLLocalDBContext(DbContextOptions<LocalDBMSSQLLocalDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cdate> Cdates { get; set; }

    public virtual DbSet<Coin> Coins { get; set; }

    public virtual DbSet<CoinDate> CoinDates { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Cdate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CDate__3214EC073E3BECF3");

            entity.ToTable("CDate");
        });

        modelBuilder.Entity<Coin>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Coin__3214EC07DE811DC3");

            entity.ToTable("Coin");

            entity.Property(e => e.AmountMade).HasColumnName("Amount Made");
            entity.Property(e => e.Description).IsRequired();
            entity.Property(e => e.ImagePath)
                .IsRequired()
                .HasDefaultValue("No_Coin_Image.jpg");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.OriginalValue)
                .HasColumnType("money")
                .HasColumnName("Original Value");
            entity.Property(e => e.RetailValue)
                .HasColumnType("money")
                .HasColumnName("Retail Value");
        });

        modelBuilder.Entity<CoinDate>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__tmp_ms_x__3214EC07847DBAEC");

            entity.ToTable("CoinDate");

            entity.HasOne(d => d.Coin).WithMany(p => p.CoinDates)
                .HasForeignKey(d => d.CoinId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("CoinFK");

            entity.HasOne(d => d.Date).WithMany(p => p.CoinDates)
                .HasForeignKey(d => d.DateId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("DateFK");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}